export const DEFAULT_ERRORS = {
  SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
};

export const AUTH_ERRORS = {
  INVALID_REGISTER_LINK: 'INVALID_REGISTER_LINK',
  ORGANISATION_IS_INACTIVE: 'ORGANISATION_IS_INACTIVE',
  ORGANISATION_NOT_FOUND: 'ORGANISATION_NOT_FOUND',
  PASSWORD_DONT_MATCH: 'PASSWORD_DONT_MATCH',
  USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
};
